# Generated by Django 3.2 on 2021-04-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cov19api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='regionCode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentCode', models.CharField(max_length=10, unique=True)),
                ('departmentName', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cov19api.region')),
            ],
        ),
    ]
